name: Build node.js wep application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install npm dependencies
          run: npm install
        - name: Build the project assets
          run: npm run build
        - name: Upload static site artifacts
          uses: actions/upload-artifact@v4
          with:
            name: static-side
            path: .next/




      